// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2S8emTPLzwvH8I4RLJlOJjuVneLYFQ7Q',
    appId: '1:743481411695:web:336ec26031cab41e0ea59a',
    messagingSenderId: '743481411695',
    projectId: 'sleep-85667',
    authDomain: 'sleep-85667.firebaseapp.com',
    storageBucket: 'sleep-85667.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMSSBlQsZltwqXWIJMr5MJugTdCWGF_kY',
    appId: '1:743481411695:android:d51b834f5c4d222e0ea59a',
    messagingSenderId: '743481411695',
    projectId: 'sleep-85667',
    storageBucket: 'sleep-85667.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBojkr79t0Hb7qAWfPFQBLhKAblRszgms',
    appId: '1:743481411695:ios:e08cc7122e7fb8bc0ea59a',
    messagingSenderId: '743481411695',
    projectId: 'sleep-85667',
    storageBucket: 'sleep-85667.appspot.com',
    iosClientId: '743481411695-78a70h6t04s3ggv9r63bgealfa7dp580.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBojkr79t0Hb7qAWfPFQBLhKAblRszgms',
    appId: '1:743481411695:ios:e08cc7122e7fb8bc0ea59a',
    messagingSenderId: '743481411695',
    projectId: 'sleep-85667',
    storageBucket: 'sleep-85667.appspot.com',
    iosClientId: '743481411695-78a70h6t04s3ggv9r63bgealfa7dp580.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );
}
